/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;
import java.awt.Component;
import java.awt.ContainerOrderFocusTraversalPolicy;
import java.awt.FocusTraversalPolicy;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import javax.swing.JFrame;


/**
 *
 * @author ASUS
 */
public class ATMachine extends javax.swing.JFrame {

    /**
     * Creates new form ATMachine
     */
    public ATMachine() {
        initComponents();
        setIndexComponentWhenTab_Enter_Key_Pressed();
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked");
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bannerLb = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtDangNhap = new javax.swing.JButton();
        jbtHuy = new javax.swing.JButton();
        jtxMatKhau = new javax.swing.JTextField();
        jtxUsername = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        bannerLb.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bannerLb.setForeground(new java.awt.Color(153, 29, 124));
        bannerLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bannerLb.setText("Chào mừng đến với ngân hàng Vietcombank!");
        bannerLb.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(bannerLb);
        bannerLb.setBounds(10, 0, 630, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(204, 0, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("User Name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 70, 60, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Mật Khẩu:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(147, 110, 60, 30);

        jbtDangNhap.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jbtDangNhap.setForeground(new java.awt.Color(0, 51, 255));
        jbtDangNhap.setText("Đăng Nhập");
        jPanel1.add(jbtDangNhap);
        jbtDangNhap.setBounds(140, 233, 130, 60);

        jbtHuy.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jbtHuy.setForeground(new java.awt.Color(0, 0, 255));
        jbtHuy.setText("Hủy");
        jbtHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtHuyActionPerformed(evt);
            }
        });
        jPanel1.add(jbtHuy);
        jbtHuy.setBounds(313, 233, 130, 60);
        jPanel1.add(jtxMatKhau);
        jtxMatKhau.setBounds(210, 110, 200, 30);
        jPanel1.add(jtxUsername);
        jtxUsername.setBounds(210, 70, 200, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 40, 630, 360);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel4.setForeground(new java.awt.Color(255, 0, 102));
        jLabel4.setText("@ Bản quyền thuộc về Ngân Hàng Vietcomebank!");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 10, 430, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 400, 630, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtHuyActionPerformed
        // TODO add your handling code here:
        this.jtxUsername.setText("");
        this.jtxMatKhau.setText("");
    }//GEN-LAST:event_jbtHuyActionPerformed

    public void setIndexComponentWhenTab_Enter_Key_Pressed(){
        ArrayList<Component> components = new ArrayList<>();
        components.add(jtxUsername);
        components.add(jtxMatKhau);
        components.add(jbtDangNhap);
        components.add(jbtHuy);        
        CustomFocusTraversalPolicy traversalPolicy = new CustomFocusTraversalPolicy(components);
        setFocusTraversalPolicy(traversalPolicy);
                
        KeyListener keyListener = new KeyListener(){
            @Override
            public void keyTyped(KeyEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void keyPressed(KeyEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                //if(e.getKeyCode() == KeyEvent.VK_ENTER){
                //    transferFocus();
                //}
            }

            @Override
             public void keyReleased(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER || e.getKeyCode() == KeyEvent.VK_TAB) {
                    Component currentComponent = getFocusOwner();
                    if (currentComponent != null) {
                        if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                            traversalPolicy.focusNextComponentWithEnterKey(currentComponent);
                        } else if (e.getKeyCode() == KeyEvent.VK_TAB) {
                            traversalPolicy.focusNextComponentWithTabKey(currentComponent);
                        }
                    }
                }
            }
        };  
     
    // add cac thanh phan can chi dinh thu tu vij tri
    jtxUsername.addKeyListener(keyListener);    
    jtxMatKhau.addKeyListener(keyListener);
    jbtDangNhap.addKeyListener(keyListener);
    jbtHuy.addKeyListener(keyListener);    
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jfAtm = new ATMachine();                
                jfAtm.setTitle("NGÂN HÀNG VIETCOMEBANK XIN KÍNH CHÀO QUÝ KHÁCH!");
                jfAtm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                jfAtm.setSize(665,490);
                jfAtm.setResizable(false);
                jfAtm.setLocationRelativeTo(null);
                jfAtm.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bannerLb;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtDangNhap;
    private javax.swing.JButton jbtHuy;
    private javax.swing.JTextField jtxMatKhau;
    private javax.swing.JTextField jtxUsername;
    // End of variables declaration//GEN-END:variables
    private static JFrame jfAtm;
    
}
